# Generated by Django 4.2.25 on 2026-03-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kruzky', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prihlaska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sprava', models.TextField(blank=True)),
                ('kruzok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kruzky.kruzok')),
            ],
        ),
    ]
